import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faChevronDown,
  faMapMarkedAlt,
} from "@fortawesome/free-solid-svg-icons";
import Guide from "../components/Guide";

export default function Home() {
  // const router = useRouter();
  // const { slug } = router.query;
  // const slug =

  const [scrolled, setScrolled] = useState(false);
  function handleScroll() {
    if (!scrolled && window.scrollY > 0) {
      setScrolled(true);
    } else if (scrolled && window.scrollY === 0) {
      setScrolled(false);
    }
  }

  useEffect(
    function () {
      if (typeof window === "undefined") return;
      window.removeEventListener("scroll", handleScroll);
      window.addEventListener("scroll", handleScroll);
    },
    [scrolled]
  );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.navWrap}>
        <div className={styles.nav}>
          <div className={styles.navLogo}>
            <FontAwesomeIcon
              icon={faMapMarkedAlt}
              className={styles.navLogoIcon}
            />{" "}
            Img Guide
          </div>
          <ul>
            {/* <li>Showcase</li> */}
            <li>Docs</li>
            <li>GitHub</li>
            <li>FAQ</li>
            <li>Pricing</li>
            <li>Demo</li>
            <li>Login</li>
            <li className={styles.navButton}>Create a Guide →</li>
          </ul>
        </div>
      </header>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Create elegant step-by-step guides in seconds
          </h1>
          <div
            className={[
              styles.example,
              scrolled && styles.exampleScrolled,
            ].join(" ")}
          >
            <div className={styles.exampleText}>check it out</div>
            <FontAwesomeIcon
              className={styles.exampleChevron}
              icon={faChevronDown}
            />
          </div>
        </main>
      </div>
      <Guide
        imgPathPrefix={"/pastudan"}
        slug={"hacker-bundle-setup"}
        edit={true}
      />
      <footer className={styles.footer}>Made with ❤ in San Francisco</footer>
    </div>
  );
}
